/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Twitter_CONSTANTS_H
#define Twitter_CONSTANTS_H

#include "Twitter_types.h"

namespace example {

class TwitterConstants {
 public:
  TwitterConstants();

};

extern const TwitterConstants g_Twitter_constants;

} // namespace

#endif
